baseURL = ""
languageCode = "en-us"
relativeURLs = true
theme = "sourgough-starter"
title = "Yu-Wen Chen"
[markup.goldmark.renderer]
unsafe = false
[[menu.about]]
identifier = "ordcidid"
name = "OrcidID"
pre = "fab fa-orcid"
url = ""
[[menu.about]]
identifier = "researchgate"
name = "ResearchGate"
pre = "fab fa-researchgate"
url = ""
[[menu.about]]
identifier = "medium"
name = "Medium"
pre = "fab fa-medium-m"
url = ""
[[menu.about]]
identifier = "googlescholar"
name = "Google Scholar"
pre = "fas fa-graduation-cap"
url = ""
[[menu.bot]]
identifier = "github"
name = "Github"
pre = "fab fa-github"
url = "https://github.com/jack-alope/"
[[menu.bot]]
identifier = "gitlab"
name = "Gitlab"
pre = "fab fa-gitlab"
url = "https://gitlab.com/jack-alope/"
[[menu.bot]]
identifier = "linkedin"
name = "LinkedIn"
pre = "fab fa-linkedin-in"
url = "https://www.linkedin.com/in/jackmurphyf/"
[[menu.link]]
identifier = "email"
name = "email@example.com"
url = "mailto:email@example.com"
[[menu.link]]
identifier = "resume"
name = "resume"
url = ""
[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
[[menu.main]]
identifier = "publications"
name = "Publications"
url = "/publications/"
[[menu.main]]
identifier = "projects"
name = "Projects"
url = "/projects/"
[params]
backgroundPath = "~/public/images/img_8864.jpg"
css = ["public/css/sourgough.css"]
dimensionCitations = true
footerOffset = -60
scholarStats = false
[taxonomies]
authors = "authors"
